# Generated by Django 4.2 on 2023-04-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("active", "active"), ("draft", "draft")],
                default="active",
                max_length=10,
            ),
        ),
    ]
